// import './instance'
// import './lifecycle'
// import './databinding'
// import './computed'
// import './directive'
// import './component/define'
// import './component/extend'
// import './component/v-model'
// import './component/feature'
import './component/provide'
